USE TEST;
DROP PROCEDURE Test_INFORMATION_SCHEMA_columns;

delimiter EOF
CREATE PROCEDURE Test_INFORMATION_SCHEMA_columns ()
BEGIN
Select *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'mysql';

Select 'Local Time: ', CURRENT_TIMESTAMP;
END
delimiter ;

